modLoader="javafml"
loaderVersion="[36,)"
license="GNU GPLv3"

[[mods]]
modId="monkmod" #mandatory
version="0.1"
displayName="Monk Mod 1.16.5"
credits="SCCWW Members"
authors="panchi64 and the monks who went on the pilgrimage with him back in 1.12"
description='''
Embark on a pilgrimage to surpass the limits of your body, mind and soul.
Learn the many ways of the monks and (eventually) become  the strongest and most powerful entity in Minecraft!
'''

[[dependencies.monkmod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.monkmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
